/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class saker_osnative_watcher_NativeWatcherService */

#ifndef _Included_saker_osnative_watcher_NativeWatcherService
#define _Included_saker_osnative_watcher_NativeWatcherService
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     saker_osnative_watcher_NativeWatcherService
	 * Method:    getImplementationClassName_native
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_saker_osnative_watcher_NativeWatcherService_getImplementationClassName_1native
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class saker_osnative_watcher_macos_SakerMacosWatchService */

#ifndef _Included_saker_osnative_watcher_macos_SakerMacosWatchService
#define _Included_saker_osnative_watcher_macos_SakerMacosWatchService
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     saker_osnative_watcher_macos_SakerMacosWatchService
	 * Method:    OpenWatcher_native
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_saker_osnative_watcher_macos_SakerMacosWatchService_OpenWatcher_1native
	(JNIEnv *, jclass);

	/*
	 * Class:     saker_osnative_watcher_macos_SakerMacosWatchService
	 * Method:    CloseWatcher_native
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_saker_osnative_watcher_macos_SakerMacosWatchService_CloseWatcher_1native
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     saker_osnative_watcher_macos_SakerMacosWatchService
	 * Method:    CreateKeyObject_native
	 * Signature: (JLjava/lang/String;ILsaker/osnative/watcher/base/SakerNativeWatchKey;)J
	 */
	JNIEXPORT jlong JNICALL Java_saker_osnative_watcher_macos_SakerMacosWatchService_CreateKeyObject_1native
	(JNIEnv *, jclass, jlong, jstring, jint, jobject);

	/*
	 * Class:     saker_osnative_watcher_macos_SakerMacosWatchService
	 * Method:    CloseKey_native
	 * Signature: (JJ)V
	 */
	JNIEXPORT void JNICALL Java_saker_osnative_watcher_macos_SakerMacosWatchService_CloseKey_1native
	(JNIEnv *, jclass, jlong, jlong);

	/*
	 * Class:     saker_osnative_watcher_macos_SakerMacosWatchService
	 * Method:    PollKey_native
	 * Signature: (JJ)V
	 */
	JNIEXPORT void JNICALL Java_saker_osnative_watcher_macos_SakerMacosWatchService_PollKey_1native
	(JNIEnv *, jclass, jlong, jlong);

	/*
	 * Class:     saker_osnative_watcher_macos_SakerMacosWatchService
	 * Method:    KeyIsValid_native
	 * Signature: (JJ)Z
	 */
	JNIEXPORT jboolean JNICALL Java_saker_osnative_watcher_macos_SakerMacosWatchService_KeyIsValid_1native
	(JNIEnv *, jclass, jlong, jlong);
	
#ifdef __cplusplus
}
#endif
#endif
